Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@bhumika-PS 
bhumika-PS
/
hyperopt
forked from hyperopt/hyperopt
0
0891
Code
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
hyperopt/.travis.yml
@bhumika-PS
bhumika-PS Update .travis.yml
Latest commit 5a91fbf 8 minutes ago
 History
 10 contributors
@maxpumperla@bhumika-PS@WeichenXu123@magdapoppins@marctorsoc@jaberg@PhilipMay@cclauss@palicand@panchalhp-db
Executable File  51 lines (41 sloc)  1.11 KB
  
os: linux

dist: focal

language: python

cache:
  directories:
    - $HOME/.cache/spark-versions

env:
  global:
    - HYPEROPT_FMIN_SEED=3
    - SPARK_VERSION=3.0.1
    - NUMPY_VERSION=1.18.1
    - IPYTHON=ipython[all]

services:
  - mongodb

jobs:
  include:
    #- name: "Run Linter (black)"
      #python: 3.9
      #install: pip install --upgrade black
      #script: black .
    - name: "Run tests on python 3.7"
      python: 3.7
    - name: "Run tests on python 3.7"
      python: 3.7
      arch: arm64
    #- name: "Run tests on python 3.8"
      #python: 3.8
    #- name: "Run tests on python 3.9"
      #python: 3.9
      #env: NUMPY_VERSION=1.19.4

install:
  - sudo apt-get remove ipython || true  # ipython is not pre-installed in Focal
  - pip install --upgrade pip setuptools wheel
  - pip install $IPYTHON numpy==$NUMPY_VERSION nose pyspark==$SPARK_VERSION scipy
  - pip install -e '.[MongoTrials, SparkTrials, ATPE, dev]'

before_script:
  - sleep 15 # mongo takes time to start
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script: pytest

after_success:
  - coveralls
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
