os: linux

dist: focal

language: python

cache:
  directories:
    - $HOME/.cache/spark-versions

env:
  global:
    - MONGODB_VERSION=2.6.10
    - HYPEROPT_FMIN_SEED=3
    - SPARK_VERSION=3.0.1
    - NUMPY_VERSION=1.18.1
    - IPYTHON=ipython[all]

services:
  - mongodb  

jobs:
  include:
    - name: "Run tests on python 3.7"
      python: 3.7
      arch: arm64

before_install:
  - sudo apt-get install gnupg
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org
  
install:
  - sudo apt-get remove ipython || true  # ipython is not pre-installed in Focal
  - pip install --upgrade pip setuptools wheel
  - pip install $IPYTHON numpy==$NUMPY_VERSION nose pyspark==$SPARK_VERSION scipy
  - pip install -e '.[MongoTrials, SparkTrials, ATPE, dev]'

before_script:
  - sleep 15 # mongo takes time to start
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script: pytest

after_success:
  - coveralls
